---
- name: Install Docker
  apt:
    name: docker.io
    state: latest
    update_cache: yes

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: latest
    update_cache: yes

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Set up Prometheus and Grafana with Docker Compose
  copy:
    content: |
      version: '3.7'
      services:
        prometheus:
          image: prom/prometheus
          ports:
            - "9090:9090"
          volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        grafana:
          image: grafana/grafana
          ports:
            - "3000:3000"
          volumes:
            - grafana_data:/var/lib/grafana
          environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
      volumes:
        grafana_data:
    dest: /home/ubuntu/docker-compose.yml
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Deploy Prometheus configuration
  template:
    src: prometheus.yml.j2
    dest: /home/ubuntu/prometheus.yml
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Start Docker Compose services
  command: docker-compose up -d
  args:
    chdir: /home/ubuntu

- name: Restart Prometheus container
  command: docker-compose restart prometheus
  args:
    chdir: /home/ubuntu
