---
- name: Install Prometheus
  apt:
    name: wget
    state: present

- name: Download Prometheus
  shell: |
    wget https://github.com/prometheus/prometheus/releases/latest/download/prometheus-*.linux-amd64.tar.gz
    tar -xzvf prometheus-*.linux-amd64.tar.gz
    sudo mv prometheus-*/prometheus /usr/local/bin/
  args:
    creates: /usr/local/bin/prometheus

- name: Copy Prometheus configuration
  template:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml

- name: Start Prometheus
  shell: |
    nohup prometheus --config.file=/etc/prometheus/prometheus.yml &
  args:
    creates: /etc/prometheus/prometheus.yml
