- name: Install NGINX
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Copy NGINX default configuration
  template:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf

- name: Restart NGINX
  service:
    name: nginx
    state: restarted

- name: Install Prometheus Node Exporter
  apt:
    name: prometheus-node-exporter
    state: latest
    update_cache: yes

- name: Start and enable Node Exporter
  service:
    name: prometheus-node-exporter
    state: started
    enabled: yes
