name: Deploy Monitoring + NGINX

on:
  push:
    branches:
      - ansible

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/my-key
          chmod 600 ~/.ssh/my-key

      - name: Disable Host Key Checking
        run: |
          echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - name: Create inventory file
        run: |
         echo "[nginx-server]" > ansible/inventories/inventory.ini
         echo "nginx ansible_host=${{ secrets.NGINX_INSTANCE_IP }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ansible/inventories/inventory.ini
         echo "[monitoring-server]" >> ansible/inventories/inventory.ini
         echo "monitoring ansible_host=<MONITORING_SERVER_IP> ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ansible/inventories/inventory.ini


      - name: Run Ansible for NGINX Server
        run: ansible-playbook -i ansible/inventories/inventory.ini ansible/playbooks/setup-nginx.yml


      - name: Run Ansible for Monitoring Server
        run: |
          ansible-playbook -i ansible/inventories/monitoring-server.yml ansible/playbooks/monitoring-server.yml
