name: Terraform Deployment

on:
  push:
    branches:
      - Infrastructure  
  pull_request:
    branches:
      - Infrastructure  

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-central-1  
      TF_VAR_profile: internebi  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5  

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/my-key
          chmod 600 ~/.ssh/my-key

      
       
      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
        id: plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/infrastructure'
        run: terraform apply -auto-approve
        

    #  - name: Destroy infra
    #    run: terraform destroy -auto-approve




        

