name: Ansible Configure

on:
  workflow_run:
    workflows: ["Terraform Deployment"]
    types:
      - completed

jobs:
  configure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}

      - name: SSH and Install Ansible
        env:
          INSTANCE_IP: ${{ secrets.INSTANCE_IP }}
        run: |
          echo "Connecting to instance at $INSTANCE_IP"
          for i in {1..5}; do
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/my-key ec2-user@$13.48.181.112 << 'EOF'
              sudo amazon-linux-extras enable ansible2
              sudo yum install -y ansible
              ansible --version
            EOF
            if [[ $? -eq 0 ]]; then break; fi
            echo "Retrying SSH connection..."
            sleep 10
          done

      - name: Run Ansible Playbooks
        env:
          INSTANCE_IP: ${{ secrets.INSTANCE_IP }}
        run: |
          echo "Running Ansible playbooks on $INSTANCE_IP"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/my-key ec2-user@$INSTANCE_IP << 'EOF'
            ansible-playbook /home/ec2-user/techtask/ansible/install_docker.yml
            ansible-playbook /home/ec2-user/techtask/ansible/deploy_monitoring.yml
            ansible-playbook /home/ec2-user/techtask/ansible/deploy_nginx.yml
          EOF
